### ISSUE TITLE
"Here's a video on how to contribute" is missing the actual video

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic-community-knowledgebase#13]
On the page https://kb.mautic.org/contributing there is the line **Need a visual explanation? Here is a video on how to contribute!** but there's no actual video.

It should be easy to fix - if anybody knows where the video is :sweat_smile:

**Comment by StoppingBuck** [comment]
@oltmanns-leuchtfeuer ?

**Comment by LeonOltmanns** [comment]
@StoppingBuck The Video is still to be recorded and hopefully will be live by next Wednesday. The contributing page itself exists since yesterday and is still WIP.

**Comment by StoppingBuck** [comment]
This seems to have been fixed (the page has moved to /contribution)

**Comment by LeonOltmanns** [comment]
Issue was resolved by adding the missing video! :)
