### ISSUE TITLE
An brief article on understanding doctrine:migrations:migrate and doctrine:schema:update

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic-community-knowledgebase#14]
Hey. On [Update Failed](https://docs.mautic.org/en/troubleshooting/update-failed) we mention both of the above CLI commands without really explaining what either does. Since it's bad practice to run CLI commands without understanding them, and understanding Symfony can be a bit of a rabbit hole, I've written a brief explanation of both. As recommended in the [KB Contribution guidelines](https://kb.mautic.org/contributing) I have put the draft on a Google Doc [here](https://docs.google.com/document/d/1GKna0XLeipTqIVf7_bdZIQwqoNSnrm4_JacftstoCZ4/edit?usp=sharing)

Proofreading, suggestions, etc. are welcome - feel free to just change anything that needs changing :slightly_smiling_face:

**Comment by LeonOltmanns** [comment]
It is live and thus, solved: https://kb.mautic.org/knowledgebase/development/understanding-doctrine-migrations-migrate-and-doctrine-schema-update :D
