### ISSUE TITLE
Links are Broken

### ISSUE THREAD

**Issue by luguenth** [mautic/mautic-community-knowledgebase#17]
Hey there,

Links are not working in this Article, written by @dennisameling 
It's pretty easy to find the right pages though, just a little heads up :) 

https://kb.mautic.org/knowledgebase/installation/how-to-install-mautic-on-a-localhost/how-to-install-mautic-using-ddev

**Comment by fakela** [comment]
@luguenth thanks for pointing out this. I have made the fix for it
