### ISSUE TITLE
Duplicated bullets on ToC

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic-community-knowledgebase#21]
Just a small snag - there seem to be extra bullets appearing in the list:

![screenshot-kb mautic org-2020 09 30-21_56_41](https://user-images.githubusercontent.com/2930593/94738859-f1500480-0367-11eb-9761-0f1b677f6295.png)

One for the snag list! :)

**Comment by LeonOltmanns** [comment]
Will take care of it as soon as possible! :)

**Comment by FEDQK** [comment]
Hi @oltmanns-leuchtfeuer 
I fixed it, please check my PR #23

**Comment by LeonOltmanns** [comment]
@FEDQK Just merged your PR, thanks alot! :)
